// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsgYfDDuPWY8t2mBzlJzQa13t6LXScF3s',
    appId: '1:528086032127:web:d5f9d7a27c51d32684b6ca',
    messagingSenderId: '528086032127',
    projectId: 'fluxproject-53ce3',
    authDomain: 'fluxproject-53ce3.firebaseapp.com',
    storageBucket: 'fluxproject-53ce3.appspot.com',
    measurementId: 'G-7KGYVC1D2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuH-iDJUjW3qcohW2ecd4L-sdi1-lNNG8',
    appId: '1:528086032127:android:70b80ab8b38b84c384b6ca',
    messagingSenderId: '528086032127',
    projectId: 'fluxproject-53ce3',
    storageBucket: 'fluxproject-53ce3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKb11HTDDcYm4iGtmFA6iIRgVSkUOhi-U',
    appId: '1:528086032127:ios:9fe03ceee7d3d3f184b6ca',
    messagingSenderId: '528086032127',
    projectId: 'fluxproject-53ce3',
    storageBucket: 'fluxproject-53ce3.appspot.com',
    iosBundleId: 'com.example.flux',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKb11HTDDcYm4iGtmFA6iIRgVSkUOhi-U',
    appId: '1:528086032127:ios:9fe03ceee7d3d3f184b6ca',
    messagingSenderId: '528086032127',
    projectId: 'fluxproject-53ce3',
    storageBucket: 'fluxproject-53ce3.appspot.com',
    iosBundleId: 'com.example.flux',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsgYfDDuPWY8t2mBzlJzQa13t6LXScF3s',
    appId: '1:528086032127:web:1a0744f422e5a02484b6ca',
    messagingSenderId: '528086032127',
    projectId: 'fluxproject-53ce3',
    authDomain: 'fluxproject-53ce3.firebaseapp.com',
    storageBucket: 'fluxproject-53ce3.appspot.com',
    measurementId: 'G-HLP6J4H90Z',
  );
}
