// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB8Y3-tmiM5wLe-e5PLQvgDXW7wbg5qn0',
    appId: '1:1062790206627:web:b9b3c9ca37fb2784765b16',
    messagingSenderId: '1062790206627',
    projectId: 'flux-91df3',
    authDomain: 'flux-91df3.firebaseapp.com',
    storageBucket: 'flux-91df3.appspot.com',
    measurementId: 'G-K618DYZWTC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZd7i8aq9PAywRZZmGZPO-DiuIqE4yZOs',
    appId: '1:1062790206627:android:c999570f211d22ce765b16',
    messagingSenderId: '1062790206627',
    projectId: 'flux-91df3',
    storageBucket: 'flux-91df3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIVWGgEtbUdJ0w2DExNbk34i8xIVHa-Yc',
    appId: '1:1062790206627:ios:3543637c313bf494765b16',
    messagingSenderId: '1062790206627',
    projectId: 'flux-91df3',
    storageBucket: 'flux-91df3.appspot.com',
    iosBundleId: 'com.example.flux',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIVWGgEtbUdJ0w2DExNbk34i8xIVHa-Yc',
    appId: '1:1062790206627:ios:3543637c313bf494765b16',
    messagingSenderId: '1062790206627',
    projectId: 'flux-91df3',
    storageBucket: 'flux-91df3.appspot.com',
    iosBundleId: 'com.example.flux',
  );
}
